"""
Skybolt - High-performance asset caching for multi-page applications

Reads the render-map.json generated by @skybolt/vite-plugin and outputs
optimized HTML tags with intelligent caching via Service Workers.
"""

from .skybolt import Skybolt

__version__ = "3.1.0"
__all__ = ["Skybolt", "__version__"]
